### ISSUE TITLE
Timer not properly cleared when spamming menus

### ISSUE THREAD

**Issue by TitanPlayz100** [TitanPlayz100/teti#10]
## Replicate
Start a game by placing a piece or pressing a button.
Spam escape to open and close the main menu.
If done fast enough, the menu will not open and another game timer starts on top of a preexisting timer.

## Possible Cause
The closing of the menu probably caused the problems because of the jank code. 
The code is mainly only there for the modal animation, so if there is another way to animate a modal closing i'll use that instead.

I'll look through commits to see when it first started and see if there is an easy fix that would be much easier to implement

Edit:
It is somewhat related to pausing game when opening menus, but feels like a xy problem because the game is still frozen when it is done so there is an underlying problem that I can't find.

**Comment by existancepy** [comment]
ok i did some testing, this bug seems to happen when you try to open the menu during its closing animation

**Comment by TitanPlayz100** [comment]
ok looks fine maybe in the future ill do something cleaner to close the modal
