### ISSUE TITLE
Lookahead nearly impossible on higher refresh rates

### ISSUE THREAD

**Issue by smooshymemes** [TitanPlayz100/teti#13]
On 240hz screens, the lookahead flash becomes 4x shorter and the fade is removed, making completing a 40L sprint nearly impossible. Please add customization for the lookahead flash and make it consistent across all screen refresh rates.

**Comment by smooshymemes** [comment]
because the flash is so short, video won't be able to capture the footage properly enough

**Comment by TitanPlayz100** [comment]
found cause, was both the refresh rate and the gravity being enabled. Fixed by turning off gravity and moving alpha changes to the 20ms gameloop
