### ISSUE TITLE
Hold box squishes pieces and it's deeply infuriating

### ISSUE THREAD

**Issue by smooshymemes** [TitanPlayz100/teti#15]
![Screenshot 2024-09-23 123222](https://github.com/user-attachments/assets/176c4d54-4fd8-4fef-bddd-07353f80827b)
please fix this its wrong

**Comment by TitanPlayz100** [comment]
Hmm it doesn't seem like I can get the issue. I noticed the font is not what I have, so maybe is hasn't loaded fully yet. Here's what I can see when I load the game.
![image](https://github.com/user-attachments/assets/02b4ad7e-b2a2-4f66-89f9-968f488880ec)

It could also be related to being on firefox or safari, I haven't really looked at that yet for the css. 

However I do know an issue with the next queue cutting off the last piece, which I'll try to fix.

**Comment by smooshymemes** [comment]
i am playing on desktop, maybe it's related to that? I am unable to test the web version, so unfortunately I can't isolate that as the cause.

**Comment by TitanPlayz100** [comment]
Ohhh I stopped updating desktop version a while back because it was way too tedious to keep both versions updated, though I do have instructions on I think the tauri branch if u wanna build a later version.

Ye unfortunately I don't really want to maintain desktop version and will stick to web.

**Comment by smooshymemes** [comment]
That's pretty unfortunate for me, as all pages ending in .github.io are blocked for me. I'm probably the only one with this issue tho, so if maintaining desktop is too hard then it's fine.

**Comment by TitanPlayz100** [comment]
just one question are pages using .vercel.app blocked for you
