### ISSUE TITLE
Gamemode customization options do not save under most circumstances

### ISSUE THREAD

**Issue by smooshymemes** [TitanPlayz100/teti#17]
Long title but BASICALLY in order to change any of the settings provided on the gamemode page, you need to:
1. Change the setting to a different number
2. Swap to a different gamemode without closing the menu

I have no idea why this is the only way to do it.
Unpausing after changing the settings just reverts them to their previous values for some reason. Really confusing imo.

**Comment by TitanPlayz100** [comment]
This is fixed on web version, as these settings are in a different menu.
I might reinstall rust to build a new version but maybe not sorry.

**Comment by smooshymemes** [comment]
Oh I should probably update my desktop client as it's likely it doesn't do that automatically. Def important to stay on the latest version.

**Comment by TitanPlayz100** [comment]
Yo I got desktop versions running again through github actions so I don't have to do any work so enjoy.

Also the exe gets marked as a virus lmao idk how to fix just use msi.
If you run mac just let me know
