### ISSUE TITLE
Cannot read properties of undefined reading "totalProgess"

### ISSUE THREAD

**Issue by SketchTurnerrr** [TitanPlayz100/teti#26]
Hey, this error occurs when clearing a line in any game mode
I'm on the 1.3.5 release

![image](https://github.com/user-attachments/assets/918e537e-8e2f-46ee-a61d-a8ba94d37c8b)

my settings
[settings.zip](https://github.com/user-attachments/files/17576694/settings.zip)

**Comment by TitanPlayz100** [comment]
Yep it was a small bug where an animation that already finished was being cleared, fixed now
