### ISSUE TITLE
Game not topping out and ending

### ISSUE THREAD

**Issue by Existance29** [TitanPlayz100/teti#4]
The game does not end when the pieces fall in place. Hard dropping in this state will end the game

Edit: This bug seems to happen when half the piece is above the line and the other half is on the board. The piece above that fails to trigger the lockPiece function
![Screenshot](https://github.com/user-attachments/assets/4a4e7fde-3661-4673-8fbe-d75d6366945f)

**Comment by Existance29** [comment]
One potential fix is to check if the minos' y position is greater than the board, then trigger a lockPiece
![image](https://github.com/user-attachments/assets/3d8e2045-47a1-432f-9694-114a8d74eba9)

**Comment by TitanPlayz100** [comment]
Fixed by existancepy (thanks).
