### ISSUE TITLE
Timer still runs after finishing

### ISSUE THREAD

**Issue by Trad0r** [TitanPlayz100/teti#6]
After finishing a 40 line game, the timer still runs. Not sure if this happens on other modes (untested).

https://github.com/user-attachments/assets/ef45cae4-97e7-4755-a7a3-bfd0068d5d54

Brower: Ungoogled Chromeium
Operating System: Steam OS (this probably doesn't matter)

**Comment by TitanPlayz100** [comment]
I don't really know how to reproduce this bug, but this might be because of some recent changes to how opening a menu pauses a game. I'll have a check and see if there is something happening.
